---
sidebar: sidebar 
permalink: faq.html 
keywords: faq, frequently asked questions 
summary: 'Trova le risposte alle domande frequenti sull"installazione, la configurazione, l"aggiornamento e la risoluzione dei problemi di Trident.' 
---
= Domande frequenti
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Trova le risposte alle domande frequenti sull'installazione, la configurazione, l'aggiornamento e la risoluzione dei problemi di Trident.



== Domande generali



=== Con quale frequenza viene rilasciato Trident?

A partire dalla versione 24,02, Trident viene rilasciato ogni quattro mesi: Febbraio, giugno e ottobre.



=== Trident supporta tutte le funzionalità rilasciate in una particolare versione di Kubernetes?

In genere, Trident non supporta le funzionalità alfa in Kubernetes. Trident potrebbe supportare le funzionalità beta all'interno delle due release Trident che seguono la release beta di Kubernetes.



=== Trident dipende da altri prodotti NetApp per il suo funzionamento?

Trident non ha dipendenze da altri prodotti software NetApp e funziona come applicazione standalone. Tuttavia, è necessario disporre di un dispositivo di storage back-end NetApp.



=== Come si ottengono i dettagli completi della configurazione di Trident?

Utilizzare il `tridentctl get` comando per ottenere ulteriori informazioni sulla configurazione di Trident.



=== Posso ottenere delle metriche sul provisioning dello storage da parte di Trident?

Sì. Endpoint Prometheus che possono essere utilizzati per raccogliere informazioni sul funzionamento di Trident, come il numero di backend gestiti, il numero di volumi sottoposti a provisioning, i byte consumati e così via. È inoltre possibile utilizzare link:https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights"^] per il monitoraggio e l'analisi.



=== L'esperienza utente cambia quando si utilizza Trident come revisioner CSI?

No. Non ci sono modifiche per quanto riguarda l'esperienza utente e le funzionalità. Il nome del fornitore utilizzato è `csi.trident.netapp.io`. Questo metodo di installazione di Trident è consigliato se si desidera utilizzare tutte le nuove funzioni fornite dalle versioni attuali e future.



== Installare e utilizzare Trident su un cluster Kubernetes



=== Trident supporta un'installazione offline da un registro privato?

Sì, Trident può essere installato offline. Fare riferimento alla link:../trident-get-started/kubernetes-deploy.html["Informazioni sull'installazione di Trident"^].



=== È possibile installare Trident BE in remoto?

Sì. Trident 18,10 e versioni successive supportano funzionalità di installazione remota da qualsiasi computer con `kubectl` accesso al cluster. Dopo aver `kubectl` verificato l'accesso (ad esempio, avviare un `kubectl get nodes` comando dal computer remoto per verificare), seguire le istruzioni di installazione.



=== Posso configurare alta disponibilità con Trident?

Trident viene installato come distribuzione Kubernetes (ReplicaSet) con un'istanza e dispone di ha incorporato. Non è necessario aumentare il numero di repliche nella distribuzione. Se il nodo in cui è installato Trident viene perso o il pod è altrimenti inaccessibile, Kubernetes ridistribuisce automaticamente il pod in un nodo integro nel cluster. Trident è solo per il piano di controllo, pertanto i pod attualmente montati non sono interessati se Trident viene riimplementato.



=== Trident ha bisogno di accedere allo spazio dei nomi kube-System?

Trident legge dal server API Kubernetes per determinare quando le applicazioni richiedono nuovi PVC, in modo che abbia bisogno di accedere al kube-system.



=== Quali sono i ruoli e Privileges utilizzati da Trident?

Il programma di installazione Trident crea un Kubernetes ClusterRole, che ha accesso specifico alle risorse PersistentVolume, PersistentVolumeClaim, StorageClass e Secret del cluster Kubernetes. Fare riferimento a link:trident-get-started/kubernetes-customize-deploy-tridentctl.html["Personalizzare l'installazione di tridentctl"^] .



=== È possibile generare localmente i file manifesti esatti utilizzati da Trident per l'installazione?

Se necessario, è possibile generare e modificare localmente i file manifesti esatti utilizzati da Trident per l'installazione. Fare riferimento alla link:trident-get-started/kubernetes-customize-deploy-tridentctl.html["Personalizzare l'installazione di tridentctl"^].



=== Posso condividere la stessa SVM di back-end ONTAP per due istanze Trident separate per due cluster Kubernetes separati?

Anche se non è consigliabile, puoi utilizzare la stessa SVM di back-end per due istanze Trident. Specificare un nome di volume univoco per ogni istanza durante l'installazione e/o specificare un parametro univoco `StoragePrefix` nel `setup/backend.json` file. In questo modo si garantisce che lo stesso FlexVol volume non venga utilizzato per entrambe le istanze.



=== È possibile installare Trident in ContainerLinux (in precedenza CoreOS)?

Trident è semplicemente un pod Kubernetes e può essere installato ovunque venga eseguito Kubernetes.



=== È possibile utilizzare Trident con NetApp Cloud Volumes ONTAP?

Sì, Trident è supportato su AWS, Google Cloud e Azure.



=== Trident funziona con Cloud Volumes Services?

Sì, Trident supporta il servizio Azure NetApp Files in Azure e il Cloud Volumes Service in GCP.



== Risoluzione dei problemi e supporto



=== NetApp supporta Trident?

Anche se Trident è open source e fornito gratuitamente, NetApp lo supporta completamente a condizione che il backend NetApp sia supportato.



=== Come si fa a inoltrare un caso di supporto?

Per inoltrare un caso di supporto, eseguire una delle seguenti operazioni:

. Contatta il tuo Support account Manager e ricevi assistenza per la richiesta di un ticket.
. Inoltrare un caso di supporto contattando https://www.netapp.com/company/contact-us/support/["Supporto NetApp"^].




=== Come si genera un bundle di log di supporto?

È possibile creare un bundle di supporto eseguendo `tridentctl logs -a`. Oltre ai log acquisiti nel bundle, acquisire il log del kubelet per diagnosticare i problemi di montaggio sul lato Kubernetes. Le istruzioni per ottenere il log di Kubernetes variano in base alla modalità di installazione di Kubernetes.



=== Cosa devo fare se devo inoltrare una richiesta per una nuova funzionalità?

Creare un problema https://github.com/NetApp/trident["Trident Github"^] e citare *RFE* nell'oggetto e nella descrizione del problema.



=== Dove posso segnalare un difetto?

Creare un problema su https://github.com/NetApp/trident["Trident Github"^]. Assicurarsi di includere tutte le informazioni e i registri necessari relativi al problema.



=== Cosa succede se ho una domanda rapida su Trident su cui ho bisogno di chiarimenti? Esiste una community o un forum?

In caso di domande, problemi o richieste, contattaci tramite il nostro Trident link:https://discord.gg/NetApp["Discordare il canale"^]o GitHub.



=== La password del mio sistema storage è cambiata e Trident non funziona più. Come posso ripristinarla?

Aggiornare la password del backend con `tridentctl update backend myBackend -f </path/to_new_backend.json> -n trident`. Sostituire `myBackend` nell'esempio con il nome backend, e. ``/path/to_new_backend.json` con il percorso verso il corretto `backend.json` file.



=== Trident non riesce a trovare il nodo Kubernetes. Come posso risolvere questo problema?

Esistono due scenari probabili per cui Trident non riesce a trovare un nodo Kubernetes. Può essere dovuto a un problema di rete all'interno di Kubernetes o a un problema DNS. Il demonset di nodi Trident eseguito su ciascun nodo Kubernetes deve essere in grado di comunicare con il controller Trident per registrare il nodo con Trident. Se si sono verificate modifiche alla rete dopo l'installazione di Trident, si riscontra questo problema solo con i nuovi nodi Kubernetes aggiunti al cluster.



=== Se il pod Trident viene distrutto, perderò i dati?

I dati non andranno persi se il pod Trident viene distrutto. I metadati Trident vengono memorizzati in oggetti CRD. Tutti i PVS forniti da Trident funzioneranno normalmente.



== Upgrade Trident (Aggiorna server)



=== È possibile eseguire l'aggiornamento da una versione precedente direttamente a una versione più recente (ignorando alcune versioni)?

NetApp supporta l'aggiornamento di Trident da una release principale alla release principale successiva. È possibile eseguire l'aggiornamento dalla versione 18.xx alla versione 19.xx, dalla versione 19.xx alla versione 20.xx e così via. Prima dell'implementazione in produzione, è necessario testare l'aggiornamento in un laboratorio.



=== È possibile eseguire il downgrade di Trident a una release precedente?

Se è necessaria una correzione per i bug osservati dopo un aggiornamento, problemi di dipendenza o un aggiornamento non riuscito o incompleto, è necessario link:trident-managing-k8s/uninstall-trident.html["Disinstallare Trident"]reinstallare la versione precedente utilizzando le istruzioni specifiche per quella versione. Questo è l'unico modo consigliato per eseguire il downgrade a una versione precedente.



== Gestione di back-end e volumi



=== È necessario definire sia la gestione che i dati in un file di definizione back-end ONTAP?

La LIF di gestione è obbligatoria. La DataLIF varia:

* ONTAP SAN (SAN iSCSI): Non specificare iSCSI. Trident utilizza link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mappa LUN selettiva ONTAP"^] per scoprire le interfacce LIF isci necessarie per stabilire una sessione multipercorso. Viene generato un avviso se `dataLIF` è definito esplicitamente. Per ulteriori informazioni, fare riferimento alla link:trident-use/ontap-san-examples.html["Opzioni ed esempi di configurazione DELLA SAN ONTAP"] sezione.
* ONTAP NAS: NetApp consiglia di specificare `dataLIF`. Se non viene fornita, Trident recupera le LIF dati dalla SVM. È possibile specificare un nome di dominio completo (FQDN) da utilizzare per le operazioni di montaggio NFS, consentendo di creare un DNS round-robin per bilanciare il carico su più LIF dati. Per ulteriori informazioni, fare riferimento alla sezionelink:trident-use/ontap-nas-examples.html["Opzioni ed esempi di configurazione del NAS ONTAP"]




=== Trident può configurare CHAP per i backend ONTAP?

Sì. Trident supporta il protocollo CHAP bidirezionale per i backend ONTAP. Questa operazione richiede l'impostazione `useCHAP=true` nella configurazione backend.



=== Come posso gestire i criteri di esportazione con Trident?

Trident è in grado di creare e gestire dinamicamente i criteri di esportazione dalla versione 20,04 in poi. Ciò consente all'amministratore dello storage di fornire uno o più blocchi CIDR nella configurazione di back-end e di aggiungere IP di nodo che rientrano in questi intervalli a un criterio di esportazione creato da Trident. In questo modo, Trident gestisce automaticamente l'aggiunta e l'eliminazione di regole per i nodi con IP all'interno dei CIDR specificati.



=== È possibile utilizzare gli indirizzi IPv6 per la gestione e DataLIF?

Trident supporta la definizione di indirizzi IPv6 per:

* `managementLIF` e. `dataLIF` Per backend NAS ONTAP.
* `managementLIF` Per backend SAN ONTAP. Impossibile specificare `dataLIF` Su un backend SAN ONTAP.


Trident deve essere installato utilizzando il flag `--use-ipv6` (per `tridentctl` l'installazione), `IPv6` (per l'operatore Trident) o `tridentTPv6` (per l'installazione di Helm) perché funzioni su IPv6.



=== È possibile aggiornare la LIF di gestione sul back-end?

Sì, è possibile aggiornare la LIF di gestione back-end utilizzando `tridentctl update backend` comando.



=== È possibile aggiornare DataLIF nel back-end?

È possibile aggiornare il DataLIF solo su `ontap-nas` e. `ontap-nas-economy`



=== Posso creare diversi backend in Trident per Kubernetes?

Trident può supportare più backend contemporaneamente, con lo stesso driver o driver diversi.



=== In che modo Trident archivia le credenziali backend?

Trident memorizza le credenziali backend come Kubernetes Secrets.



=== In che modo Trident seleziona un backend specifico?

Se non è possibile utilizzare gli attributi di backend per selezionare automaticamente i pool giusti per una classe, il `storagePools` e. `additionalStoragePools` i parametri vengono utilizzati per selezionare un set specifico di pool.



=== Come posso garantire che Trident non esegua il provisioning da un backend specifico?

Il `excludeStoragePools` parametro viene utilizzato per filtrare l'insieme di pool utilizzato da Trident per il provisioning e rimuoverà tutti i pool corrispondenti.



=== Se esistono più backend dello stesso tipo, in che modo Trident seleziona quale backend utilizzare?

Se sono presenti più backend configurati dello stesso tipo, Trident seleziona il backend appropriato in base ai parametri presenti in `StorageClass` e `PersistentVolumeClaim`. Ad esempio, se sono presenti più backend di driver ONTAP-nas, Trident tenta di far corrispondere i parametri in `StorageClass` e combinati e `PersistentVolumeClaim` di far corrispondere un backend in grado di soddisfare i requisiti elencati in `StorageClass` e `PersistentVolumeClaim`. Se sono presenti più backend che corrispondono alla richiesta, Trident seleziona uno di essi in modo casuale.



=== Trident supporta CHAP bidirezionale con Element/SolidFire?

Sì.



=== In che modo Trident implementa Qtree su un volume ONTAP? Quanti Qtree possono essere implementati su un singolo volume?

 `ontap-nas-economy`Il driver crea fino a 200 Qtree nella stessa FlexVol volume (configurabile tra 50 e 300), 100.000 Qtree per nodo del cluster e 2,4M TB per cluster. Quando si immette un nuovo `PersistentVolumeClaim` che viene gestito dal driver Economy, il conducente cerca di vedere se esiste già un FlexVol volume in grado di servire il nuovo Qtree. Se il FlexVol volume non esiste e può servire la Qtree, viene creato un nuovo FlexVol volume.



=== Come si impostano le autorizzazioni Unix per i volumi forniti su NAS ONTAP?

È possibile impostare autorizzazioni Unix sul volume fornito da Trident impostando un parametro nel file di definizione backend.



=== Come posso configurare un set esplicito di opzioni di montaggio NFS di ONTAP durante il provisioning di un volume?

Per impostazione predefinita, Trident non imposta le opzioni di montaggio su alcun valore con Kubernetes. Per specificare le opzioni di montaggio nella classe di archiviazione Kubernetes, seguire l'esempio fornito link:https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-ontapnas-k8s1.8-mountoptions.yaml["qui"^].



=== Come si impostano i volumi sottoposti a provisioning in base a una policy di esportazione specifica?

Per consentire agli host appropriati di accedere a un volume, utilizzare `exportPolicy` parametro configurato nel file di definizione del backend.



=== Come si imposta la crittografia dei volumi tramite Trident con ONTAP?

È possibile impostare la crittografia sul volume fornito da Trident utilizzando il parametro di crittografia nel file di definizione del backend. Per ulteriori informazioni, consultare: link:trident-reco/security-reco.html#use-trident-with-nve-and-nae["Come funziona Trident con NVE e NAE"]



=== Qual è il modo migliore per implementare QoS per ONTAP tramite Trident?

Utilizzare `StorageClasses` Per implementare QoS per ONTAP.



=== Come è possibile specificare il thin provisioning o il thick provisioning tramite Trident?

I driver ONTAP supportano il thin provisioning o il thick provisioning. Per impostazione predefinita, i driver ONTAP passano al thin provisioning. Se si desidera eseguire il thick provisioning, è necessario configurare il file di definizione del backend o il `StorageClass`. Se entrambi sono configurati, `StorageClass` ha la precedenza. Configurare quanto segue per ONTAP:

. Acceso `StorageClass`, impostare `provisioningType` attributo come thick.
. Nel file di definizione del backend, attivare i volumi thick impostando `backend spaceReserve parameter` come volume.




=== Come si può verificare che i volumi utilizzati non vengano cancellati anche se si elimina accidentalmente il PVC?

La protezione PVC viene attivata automaticamente su Kubernetes a partire dalla versione 1.10.



=== È possibile far crescere il numero di PVC NFS creati da Trident?

Sì. È possibile espandere un PVC creato da Trident. Tenere presente che la crescita automatica del volume è una funzione di ONTAP non applicabile a Trident.



=== È possibile importare un volume in modalità SnapMirror Data Protection (DP) o offline?

L'importazione del volume non riesce se il volume esterno è in modalità DP o non è in linea. Viene visualizzato il seguente messaggio di errore:

[listing]
----
Error: could not import volume: volume import failed to get size of volume: volume <name> was not found (400 Bad Request) command terminated with exit code 1.
Make sure to remove the DP mode or put the volume online before importing the volume.
----


=== Come viene tradotta la quota di risorse in un cluster NetApp?

La quota delle risorse di storage di Kubernetes dovrebbe funzionare finché lo storage NetApp dispone di capacità. Quando lo storage NetApp non è in grado di rispettare le impostazioni della quota Kubernetes a causa della mancanza di capacità, Trident tenta di eseguire il provisioning, con errori che vengono eliminati.



=== È possibile creare snapshot del volume utilizzando Trident?

Sì. La creazione di snapshot di volumi on-demand e di volumi persistenti da Snapshot sono supportate da Trident. Per creare PVS dalle istantanee, assicurarsi che il `VolumeSnapshotDataSource` gate delle funzioni sia stato attivato.



=== Quali sono i driver che supportano le snapshot di volume Trident?

Da oggi, il supporto snapshot on-demand è disponibile per il nostro `ontap-nas` , `ontap-nas-flexgroup` , `ontap-san` , `ontap-san-economy` , `solidfire-san` , `gcp-cvs` , E `azure-netapp-files` driver backend.



=== Come è possibile eseguire un backup snapshot di un volume dotato di provisioning Trident con ONTAP?

Disponibile in `ontap-nas`, `ontap-san`, e. `ontap-nas-flexgroup` driver. È inoltre possibile specificare un `snapshotPolicy` per `ontap-san-economy` Driver a livello di FlexVol.

Questa operazione è disponibile anche `ontap-nas-economy` sui driver, ma non sulla granularità a livello di FlexVol volume e non a livello di qtree. Per abilitare la possibilità di creare snapshot dei volumi forniti da Trident, imposta l'opzione del parametro backend `snapshotPolicy` sulla policy dello snapshot desiderata, come definito nel back-end ONTAP. Trident non conosce istantanee scattate dallo storage controller.



=== È possibile impostare una percentuale di riserva di snapshot per un volume sottoposto a provisioning tramite Trident?

Sì, è possibile riservare una percentuale specifica di spazio su disco per l'archiviazione delle copie snapshot tramite Trident impostando l' `snapshotReserve`attributo nel file di definizione backend. Se è stato configurato `snapshotPolicy` e `snapshotReserve` nel file di definizione backend, la percentuale di riserva snapshot viene impostata in base alla `snapshotReserve` percentuale indicata nel file backend. Se il `snapshotReserve` numero di percentuale non viene menzionato, ONTAP utilizza per impostazione predefinita la percentuale di riserva dello snapshot come 5. Se l' `snapshotPolicy`opzione è impostata su nessuno, la percentuale di riserva istantanea è impostata su 0.



=== È possibile accedere direttamente alla directory di snapshot del volume e copiare i file?

Sì, è possibile accedere alla directory di snapshot sul volume fornito da Trident impostando `snapshotDir` nel file di definizione back-end.



=== Posso configurare SnapMirror per i volumi tramite Trident?

Attualmente, SnapMirror deve essere impostato esternamente utilizzando l'interfaccia CLI di ONTAP o Gestione di sistema di OnCommand.



=== Come si ripristinano i volumi persistenti in uno snapshot ONTAP specifico?

Per ripristinare un volume in uno snapshot ONTAP, attenersi alla seguente procedura:

. Interrompere il pod dell'applicazione che utilizza il volume persistente.
. Ripristinare lo snapshot richiesto tramite l'interfaccia utente di ONTAP o Gestione di sistema di OnCommand.
. Riavviare il pod applicazioni.




=== Trident può eseguire il provisioning di volumi su SVM con un mirror di condivisione del carico configurato?

È possibile creare mirror di condivisione del carico per i volumi root delle SVM che servono dati su NFS. ONTAP aggiorna automaticamente i mirror di condivisione del carico per i volumi creati da Trident. Ciò potrebbe causare ritardi nell'installazione dei volumi. Quando si creano più volumi utilizzando Trident, il provisioning di un volume dipende dall'aggiornamento del mirror di condivisione del carico da parte di ONTAP.



=== Come è possibile separare l'utilizzo della classe di storage per ciascun cliente/tenant?

Kubernetes non consente classi di storage negli spazi dei nomi. Tuttavia, è possibile utilizzare Kubernetes per limitare l'utilizzo di una classe di storage specifica per spazio dei nomi utilizzando le quote delle risorse di storage, che sono per spazio dei nomi. Per negare l'accesso a uno spazio dei nomi specifico a uno storage specifico, impostare la quota di risorse su 0 per tale classe di storage.
