---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-trident.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: 'Trident segue una cadenza di quattro mesi per le release, fornendo tre importanti release ogni anno solare. Ogni nuova release si basa sulle release precedenti, fornendo nuove funzionalità e miglioramenti delle performance, oltre a correzioni di bug e miglioramenti. Si consiglia di effettuare l"aggiornamento almeno una volta all"anno per sfruttare le nuove funzioni di Trident.' 
---
= Upgrade Trident (Aggiorna server)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire dalla release 24,02, Trident segue una cadenza di quattro mesi, fornendo tre release principali ogni anno solare. Ogni nuova release si basa sulle release precedenti e offre nuove funzionalità, miglioramenti delle prestazioni, correzioni di bug e miglioramenti. Vi consigliamo di effettuare l'aggiornamento almeno una volta all'anno per usufruire delle nuove funzioni di Trident.



== Considerazioni prima dell'aggiornamento

Quando si effettua l'aggiornamento alla versione più recente di Trident, tenere presente quanto segue:

* Dovrebbe essere installata una sola istanza di Trident in tutti gli spazi dei nomi di un determinato cluster Kubernetes.
* Trident 23,07 e versioni successive richiedono snapshot di volume v1 e non supportano più snapshot alfa o beta.
* Se è stato creato Cloud Volumes Service per Google Cloud in link:../trident-use/gcp.html#learn-about-trident-support-for-cloud-volumes-service-for-google-cloud["Tipo di servizio CVS"], è necessario aggiornare la configurazione backend per utilizzare il `standardsw` livello di servizio o `zoneredundantstandardsw` durante l'aggiornamento da Trident 23,01. Il mancato aggiornamento di `serviceLevel` nel backend potrebbe causare un errore dei volumi. Per ulteriori informazioni, fare riferimento alla link:../trident-use/gcp.html#cvs-service-type-examples["Esempi di tipo di servizio CVS"] sezione.
* Quando si esegue l'aggiornamento, è importante fornire `parameter.fsType` in `StorageClasses` usato da Trident. Puoi eliminare e ricreare `StorageClasses` senza interrompere i volumi preesistenti.
+
** Si tratta di un requisito **** per l'applicazione https://kubernetes.io/docs/tasks/configure-pod-container/security-context/["contesti di sicurezza"^] Per volumi SAN.
** La directory https://github.com/NetApp/trident/tree/master/trident-installer/sample-input[sample input^] contiene esempi, come https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-basic.yaml.templ[`storage-class-basic.yaml.templ`^] e link:https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-bronze-default.yaml[`storage-class-bronze-default.yaml`^].
** Per ulteriori informazioni, fare riferimento a. link:../trident-rn.html["Problemi noti"].






== Fase 1: Selezionare una versione

Le versioni Trident seguono una convenzione di denominazione basata sulla data `YY.MM`, dove "YY" è l'ultima cifra dell'anno e "MM" è il mese. I rilasci di DOT seguono una `YY.MM.X` convenzione, dove "X" è il livello di patch. Selezionare la versione a cui eseguire l'aggiornamento in base alla versione da cui si sta eseguendo l'aggiornamento.

* È possibile eseguire un aggiornamento diretto a qualsiasi release di destinazione che si trova all'interno di una finestra di quattro release della versione installata. Ad esempio, è possibile aggiornare direttamente da 24,06 (o qualsiasi versione a 24,06 punti) a 25,02.
* Se si sta eseguendo l'aggiornamento da una release al di fuori della finestra a quattro release, eseguire un aggiornamento in più fasi. Utilizzare le istruzioni di aggiornamento per il link:../earlier-versions.html["versione precedente"] quale si sta eseguendo l'aggiornamento per passare alla versione più recente adatta alla finestra a quattro release. Ad esempio, se si utilizza 23,01 e si desidera eseguire l'aggiornamento a 25,02:
+
.. Primo aggiornamento da 23,01 a 24,02.
.. Quindi, eseguire l'aggiornamento da 24,02 a 25,02.





NOTE: Quando si esegue l'aggiornamento utilizzando l'operatore Trident su OpenShift Container Platform, è necessario eseguire l'aggiornamento a Trident 21.01.1 o versione successiva. L'operatore Trident rilasciato con 21.01.0 contiene un problema noto che è stato risolto nel 21.01.1. Per ulteriori informazioni, fare riferimento alla https://github.com/NetApp/trident/issues/517["Dettagli del problema su GitHub"^].



== Fase 2: Determinare il metodo di installazione originale

Per determinare quale versione è stata utilizzata per l'installazione originale di Trident:

. Utilizzare `kubectl get pods -n trident` esaminare i pod.
+
** Se non è presente alcun pannello operatore, Trident è stato installato utilizzando `tridentctl`.
** Se è presente un quadro di comando, Trident è stato installato utilizzando l'operatore Trident manualmente o utilizzando Helm.


. Se è presente un pannello operatore, utilizzare `kubectl describe torc` per determinare se Trident è stato installato utilizzando Helm.
+
** Se è presente un'etichetta Helm, Trident è stato installato utilizzando Helm.
** Se non è presente alcuna etichetta Helm, Trident è stato installato manualmente utilizzando l'operatore Trident.






== Fase 3: Selezionare un metodo di aggiornamento

In genere, è necessario eseguire l'aggiornamento utilizzando lo stesso metodo utilizzato per l'installazione iniziale, tuttavia è possibile link:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["passare da un metodo di installazione all'altro"]. Sono disponibili due opzioni per aggiornare Trident.

* link:upgrade-operator.html["Eseguire l'aggiornamento utilizzando l'operatore Trident"]
+

TIP: Ti consigliamo di rivedere link:upgrade-operator-overview.html["Comprendere il flusso di lavoro di aggiornamento dell'operatore"] prima di eseguire l'aggiornamento con l'operatore.

* 

