---
sidebar: sidebar 
permalink: trident-use/anf.html 
keywords: trident backend, azure netapp files, smb volumes, smb, windows, drivers, access modes, rwo, rwx, rwp, rwop, file system, aks, managed identities, azure, azure government 
summary: 'Configura Azure NetApp Files come backend per Trident e utilizza volumi NFS o SMB. Trident supporta le identità gestite e l"identità dei carichi di lavoro sui cluster AKS.' 
---
= Configurare un backend Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizza Azure NetApp Files come backend per Trident. Questo backend supporta volumi NFS e SMB. Trident supporta identità gestite e workload identity per i cluster Azure Kubernetes Service (AKS).



== Ambienti cloud Azure supportati

Trident supporta backend Azure NetApp Files in più ambienti cloud di Azure.

I cloud Azure supportati includono:

* Azure Commercial
* Azure Government (Azure Government / MAG)


Quando distribuisci Trident o configuri un backend Azure NetApp Files, assicurati che Azure Resource Manager e gli endpoint di autenticazione corrispondano al tuo ambiente cloud di Azure.



== Esaminare il supporto del driver Azure NetApp Files

Trident fornisce il seguente driver di storage Azure NetApp Files.

Le modalità di accesso supportate includono _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX) e _ReadWriteOncePod_ (RWOP).

[cols="2,1,1,2,2"]
|===
| Driver | Protocollo | VolumeMode | Modalità di accesso supportate | File system supportati 


| `azure-netapp-files`  a| 
NFS
PMI
 a| 
Filesystem
 a| 
RWO, ROX, RWX, RWOP
 a| 
`nfs`, `smb`

|===


== Considerazioni sulla revisione

* Azure NetApp Files non supporta volumi inferiori a 50 GiB. Trident crea un volume da 50 GiB quando viene richiesto un volume più piccolo.
* Trident supporta volumi SMB montati su pod in esecuzione solo sui nodi Windows.
* Le distribuzioni di Azure NetApp Files nei cloud Azure non commerciali richiedono endpoint di Azure Resource Manager e di autenticazione specifici per il cloud. Assicurarsi che Trident e qualsiasi configurazione di backend utilizzino gli endpoint appropriati per l'ambiente cloud Azure.




== Usa identità gestite per AKS

Trident supporta link:https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview["identità gestite"^] per i cluster AKS.

Se si utilizza  `tridentctl` per creare o gestire backend di Azure NetApp Files, assicurarsi che sia configurato per il corretto ambiente cloud di Azure.

Per utilizzare le identità gestite, è necessario avere:

* Un cluster Kubernetes implementato utilizzando AKS
* Identità gestite configurate sul cluster Kubernetes AKS
* Trident installato con  `cloudProvider` impostato su  `"Azure"`


[role="tabbed-block"]
====
.Operatore Trident
--
Modifica `tridentorchestrator_cr.yaml` e imposta `cloudProvider` su `"Azure"`.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "Azure"
----
--
.Timone
--
Il seguente esempio installa Trident e imposta  `cloudProvider` utilizzando la variabile di ambiente  `$CP`:

[listing]
----
helm install trident trident-operator-100.2506.0.tgz --create-namespace --namespace <trident-namespace> --set cloudProvider=$CP
----
--
.<code>tridentctl</code>
--
Il seguente esempio installa Trident e imposta il flag `cloud-provider` su `Azure`:

[listing]
----
tridentctl install --cloud-provider="Azure" -n trident
----
--
====


== Usa l'identità del carico di lavoro per AKS

Workload identity consente ai pod Kubernetes di accedere alle risorse di Azure autenticandosi come workload identity.

Se si utilizza  `tridentctl` per creare o gestire backend di Azure NetApp Files, assicurarsi che sia configurato per il corretto ambiente cloud di Azure.

Per utilizzare l'identità del carico di lavoro, è necessario disporre di:

* Un cluster Kubernetes implementato utilizzando AKS
* Identità del workload e issuer oidc configurati nel cluster AKS Kubernetes
* Trident installato con  `cloudProvider` impostato su  `"Azure"` e  `cloudIdentity` impostato sul valore dell'identità del carico di lavoro


[role="tabbed-block"]
====
.Operatore Trident
--
Modifica `tridentorchestrator_cr.yaml` e imposta `cloudProvider` su `"Azure"`. Imposta `cloudIdentity` su `azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx`.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "Azure"
  cloudIdentity: 'azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx' # Edit
----
--
.Timone
--
Imposta i valori per i flag *cloud-provider (CP)* e *cloud-identity (CI)* utilizzando le seguenti variabili di ambiente:

`export CP="Azure"`
`export CI="'azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'"`

Il seguente esempio installa Trident e imposta  `cloudProvider` usando  `$CP` e imposta  `cloudIdentity` usando  `$CI`:

[listing]
----
helm install trident trident-operator-100.6.0.tgz --set cloudProvider=$CP --set cloudIdentity="$CI"
----
--
.<code>tridentctl</code>
--
Imposta i valori per i flag *cloud provider* e *cloud identity* utilizzando le seguenti variabili di ambiente:

`export CP="Azure"`
`export CI="azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"`

Il seguente esempio installa Trident e imposta  `cloud-provider` a  `$CP` e  `cloud-identity` a  `$CI`:

[listing]
----
tridentctl install --cloud-provider=$CP --cloud-identity="$CI" -n trident
----
--
====