---
sidebar: sidebar 
permalink: trident-use/fcp.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes, worker node, iscsi, scsi, scsi over fc, fibre channel, fcp, kubernetes clusters, self-healing, healing. 
summary:  
---
= Supporto Fibre Channel (FC)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Da oggi è possibile utilizzare il protocollo Fibre Channel (FC) con Trident per il provisioning e la gestione delle risorse di storage sul sistema ONTAP.

*SCSI over Fibre Channel (FC) è una funzione di anteprima tecnica nella versione Trident 24,10.*

Il protocollo Fibre Channel è ampiamente adottato in ambienti di storage Enterprise grazie alle sue elevate prestazioni, affidabilità e scalabilità. Fornisce un canale di comunicazione solido ed efficiente per i dispositivi di storage, consentendo trasferimenti di dati veloci e sicuri. Utilizzando SCSI su Fibre Channel, è possibile sfruttare l'infrastruttura di storage basata su SCSI esistente e sfruttare al contempo le prestazioni elevate e le capacità a lunga distanza offerte da Fibre Channel. Consente il consolidamento delle risorse di storage e la creazione di reti SAN (Storage Area Network) scalabili ed efficienti, in grado di gestire grandi quantità di dati con bassa latenza.

Utilizzando la funzionalità FC con Trident, è possibile: * Eseguire il provisioning dinamico di PVC utilizzando una specifica di implementazione. * Acquisire snapshot di volume e creare un nuovo volume dallo snapshot. * Clona un FC-PVC esistente. * Ridimensionare un volume già distribuito.



== Prerequisiti

Configurare le impostazioni di rete e del nodo richieste per FC.



=== Impostazioni di rete

. Ottenere il WWPN delle interfacce di destinazione. Per ulteriori informazioni, fare riferimento link:..https://docs.netapp.com/us-en/ontap-cli//network-interface-show.html["visualizzazione dell'interfaccia di rete"^] a.
. Ottenere il WWPN per le interfacce su iniziatore (host).
+
Fare riferimento alle utility del sistema operativo host corrispondenti.

. Configurare lo zoning sullo switch FC utilizzando i WWPN dell'host e della destinazione.
+
Per informazioni, fare riferimento alla documentazione relativa del fornitore dell'interruttore.

+
Per ulteriori informazioni, consultare la seguente documentazione di ONTAP:

+
** https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["Panoramica dello zoning FCoE e Fibre Channel"^]
** https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html["Modalità di configurazione degli host SAN FC FC-NVMe"^]






=== Preparare il nodo di lavoro

Tutti i nodi di lavoro nel cluster Kubernetes devono essere in grado di montare i volumi forniti per i pod. Per preparare i nodi di lavoro per la FC, è necessario installare gli strumenti richiesti.

.Installare gli strumenti FC
Installa gli strumenti FC utilizzando i comandi del tuo sistema operativo.

* Quando si utilizzano nodi di lavoro che eseguono RHEL/RedHat CoreOS con iSCSI PVS, specificare `discard` MountOption in StorageClass per eseguire la rigenerazione dello spazio inline. Fare riferimento a. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Documentazione RedHat"^].


[role="tabbed-block"]
====
.RHEL 8+
--
. Installare i seguenti pacchetti di sistema:
+
[listing]
----
sudo yum install -y lsscsi iscsi-initiator-utils device-mapper-multipath
----
. Verificare che la versione di iscsi-initiator-utils sia 6.2.0.874-2.el7 o successiva:
+
[listing]
----
rpm -q iscsi-initiator-utils
----
. Abilitare il multipathing:
+
[listing]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: Assicurarsi `etc/multipath.conf` contiene `find_multipaths no` sotto `defaults`.

. Assicurarsi che `iscsid` e. `multipathd` sono in esecuzione:
+
[listing]
----
sudo systemctl enable --now iscsid multipathd
----
. Attivare e avviare `iscsi`:
+
[listing]
----
sudo systemctl enable --now iscsi
----


--
.Ubuntu
--
. Installare i seguenti pacchetti di sistema:
+
[listing]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. Verificare che la versione Open-iscsi sia 2.0.874-5ubuntu2.10 o successiva (per il bionico) o 2.0.874-7.1ubuntu6.1 o successiva (per il focale):
+
[listing]
----
dpkg -l open-iscsi
----
. Impostare la scansione su manuale:
+
[listing]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. Abilitare il multipathing:
+
[listing]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: Assicurarsi `etc/multipath.conf` contiene `find_multipaths no` sotto `defaults`.

. Assicurarsi che `open-iscsi` e. `multipath-tools` sono abilitati e in esecuzione:
+
[listing]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----
+

NOTE: Per Ubuntu 18.04, è necessario rilevare le porte di destinazione con `iscsiadm` prima di iniziare `open-iscsi` Per avviare il daemon iSCSI. In alternativa, è possibile modificare `iscsi` servizio da avviare `iscsid` automaticamente.



--
====


== Creare una configurazione backend

Creare un backend Trident per il `ontap-san` driver e `fcp` come sanType.

Fare riferimento a:

* link:..trident-use/ontap-san-prep.html["Prepararsi a configurare il backend con i driver SAN ONTAP"]
* link:..trident-use/ontap-san-examples.html["Opzioni ed esempi di configurazione DELLA SAN ONTAP"^]


.Esempio di configurazione backend con FC
[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-san
spec:
  version: 1
  backendName: ontap-san-backend
  storageDriverName: ontap-san
  managementLIF: 10.0.0.1
  sanType: fcp
  svm: trident_svm
  credentials:
    name: backend-tbc-ontap-san-secret
----


== Creare una classe di storage

Per ulteriori informazioni, fare riferimento a:

* link:..trident-docker/stor-config.html["Opzioni di configurazione dello storage"^]


.Esempio di classe di storage
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fcp-sc
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  protocol: "fcp"
  storagePool: "aggr1"
allowVolumeExpansion: True
----