---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: 'Utilizzando Trident con Amazon FSX per NetApp ONTAP, puoi assicurarti che i tuoi cluster Kubernetes in esecuzione in Amazon Elastic Kubernetes Service (EKS) possano effettuare il provisioning di volumi persistenti di file e blocchi supportati da ONTAP.' 
---
= Installare Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident ottimizza la gestione dello storage di Amazon FSX per NetApp ONTAP in Kubernetes per permettere a sviluppatori e amministratori di concentrarsi sull'implementazione dell'applicazione.

È possibile installare Trident utilizzando uno dei seguenti metodi:

* Timone
* Componente aggiuntivo EKS


Se si desidera utilizzare la funzionalità snapshot, installare il componente aggiuntivo del controller snapshot CSI. Per ulteriori informazioni, fare riferimento link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["Attiva la funzionalità snapshot per volumi CSI"^] a.



== Installare Trident tramite helm

[role="tabbed-block"]
====
.Identità del pod
--
. Aggiungere il repository Trident Helm:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Installa Trident utilizzando il seguente esempio:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
È possibile utilizzare il `helm list` comando per esaminare i dettagli dell'installazione come nome, spazio dei nomi, grafico, stato, versione dell'app e numero di revisione.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.Associazione dell'account di servizio (IRSA)
--
. Aggiungere il repository Trident Helm:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Imposta i valori per *cloud provider* e *cloud identity*:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
È possibile utilizzare il `helm list` comando per esaminare i dettagli dell'installazione come nome, spazio dei nomi, grafico, stato, versione dell'app e numero di revisione.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2506.0    25.06.0
----


--
====
[NOTE]
====
Se prevedi di utilizzare iSCSI, assicurati che iSCSI sia abilitato sul computer client. Se utilizzi il sistema operativo AL2023 Worker node, puoi automatizzare l'installazione del client iSCSI aggiungendo il parametro node prep nell'installazione di helm:

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== Installare Trident tramite il componente aggiuntivo EKS

Il componente aggiuntivo Trident EKS include le più recenti patch di sicurezza, correzioni di bug ed è convalidato da AWS per funzionare con Amazon EKS. Il componente aggiuntivo EKS ti consente di garantire in modo coerente che i tuoi cluster Amazon EKS siano sicuri e stabili e di ridurre la quantità di lavoro da svolgere per installare, configurare e aggiornare i componenti aggiuntivi.



=== Prerequisiti

Prima di configurare il componente aggiuntivo Trident per AWS EKS, assicurati di disporre di quanto segue:

* Un account cluster Amazon EKS con abbonamento add-on
* Autorizzazioni AWS nel marketplace AWS:
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* Tipo di ami: Amazon Linux 2 (AL2_x86_64) o Amazon Linux 2 Arm (AL2_ARM_64)
* Tipo di nodo: AMD o ARM
* Un file system Amazon FSX per NetApp ONTAP esistente




=== Attiva il componente aggiuntivo Trident per AWS

[role="tabbed-block"]
====
.Console di gestione
--
. Aprire la console Amazon EKS all'indirizzo https://console.aws.amazon.com/eks/home#/clusters[].
. Nel riquadro di spostamento di sinistra, selezionare *Cluster*.
. Selezionare il nome del cluster per il quale si desidera configurare il componente aggiuntivo NetApp Trident CSI.
. Selezionare *componenti aggiuntivi*, quindi selezionare *Ottieni altri componenti aggiuntivi*.
. Per selezionare il componente aggiuntivo, segui questi passaggi:
+
.. Scorri verso il basso fino alla sezione *Componenti aggiuntivi di AWS Marketplace* e digita *"Trident”* nella casella di ricerca.
.. Selezionare la casella di controllo nell'angolo in alto a destra della casella Trident by NetApp.
.. Selezionare *Avanti*.


. Nella pagina Impostazioni *Configura componenti aggiuntivi selezionati*, effettuare le seguenti operazioni:
+

NOTE: *Salta questi passaggi se utilizzi l'associazione Pod Identity.*

+
.. Selezionare la *versione* che si desidera utilizzare.
.. Se si utilizza l'autenticazione IRSA, assicurarsi di impostare i valori di configurazione disponibili nelle impostazioni di configurazione facoltative:
+
*** Selezionare la *versione* che si desidera utilizzare.
*** Segui lo *schema di configurazione del componente aggiuntivo* e imposta il parametro *configurationValues* nella sezione *Valori di configurazione* sul role-arn creato nel passaggio precedente (il valore deve essere nel seguente formato):




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
  "cloudProvider": "AWS"

}
----
+
Se si seleziona Sovrascrivi per il metodo di risoluzione dei conflitti, una o più impostazioni per il componente aggiuntivo esistente possono essere sovrascritte con le impostazioni del componente aggiuntivo Amazon EKS. Se non si attiva questa opzione e si verifica un conflitto con le impostazioni esistenti, l'operazione non riesce. È possibile utilizzare il messaggio di errore risultante per risolvere il conflitto. Prima di selezionare questa opzione, assicurati che il componente aggiuntivo Amazon EKS non gestisca le impostazioni da gestire in autonomia.

. Scegliere *Avanti*.
. Nella pagina *Rivedi e Aggiungi*, scegliere *Crea*.
+
Al termine dell'installazione del componente aggiuntivo, viene visualizzato il componente aggiuntivo installato.



--
.CLI AWS
--
*1. Crea il  `add-on.json` file*:

*Per l'identità del pod, utilizzare il seguente formato*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
}
----
*Per l'autenticazione IRSA, utilizzare il seguente formato*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: Sostituire `<role ARN>` con l'ARN del ruolo creato nel passaggio precedente.

*2. Installa il componente aggiuntivo Trident EKS.*

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksctl
--
Il seguente comando di esempio installa il componente aggiuntivo Trident EKS:

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== Aggiornare il componente aggiuntivo Trident EKS

[role="tabbed-block"]
====
.Console di gestione
--
. Aprire la console Amazon EKS https://console.aws.amazon.com/eks/home#/clusters[].
. Nel riquadro di spostamento di sinistra, selezionare *Cluster*.
. Selezionare il nome del cluster per il quale si desidera aggiornare il componente aggiuntivo NetApp Trident CSI.
. Selezionare la scheda *componenti aggiuntivi*.
. Selezionare *Trident by NetApp*, quindi selezionare *Modifica*.
. Nella pagina *Configure Trident by* (Configura server tramite NetApp*), procedere come segue:
+
.. Selezionare la *versione* che si desidera utilizzare.
.. Espandere le *impostazioni di configurazione opzionali* e modificarle secondo necessità.
.. Selezionare *Save Changes* (Salva modifiche).




--
.CLI AWS
--
Nell'esempio seguente viene aggiornato il componente aggiuntivo EKS:

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.6.0-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksctl
--
* Controllare la versione corrente del componente aggiuntivo FSxN Trident CSI. Sostituire `my-cluster` con il nome del cluster.
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*Esempio di output:*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.6.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* Aggiornare il componente aggiuntivo alla versione restituita in AGGIORNAMENTO DISPONIBILE nell'output del passaggio precedente.
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.6.0-eksbuild.1 --cluster my-cluster --force
----


Se si rimuove l' `--force` opzione e una delle impostazioni del componente aggiuntivo Amazon EKS è in conflitto con le impostazioni esistenti, l'aggiornamento del componente aggiuntivo Amazon EKS non viene eseguito correttamente; viene visualizzato un messaggio di errore che aiuta a risolvere il conflitto. Prima di specificare questa opzione, assicurati che il componente aggiuntivo Amazon EKS non gestisca le impostazioni da gestire, perché queste impostazioni vengono sovrascritte con questa opzione. Per ulteriori informazioni sulle altre opzioni per questa impostazione, vedere link:https://eksctl.io/usage/addons/["Componenti aggiuntivi"]. Per ulteriori informazioni su Amazon EKS Kubernetes Field management, consulta link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Gestione sul campo di Kubernetes"].

--
====


=== Disinstallare/rimuovere il componente aggiuntivo Trident EKS

Hai due opzioni per rimuovere un add-on Amazon EKS:

* *Mantieni il software aggiuntivo sul tuo cluster* – questa opzione rimuove la gestione Amazon EKS di qualsiasi impostazione. Inoltre, rimuove la possibilità per Amazon EKS di informarti degli aggiornamenti e di aggiornare automaticamente il componente aggiuntivo Amazon EKS dopo l'avvio di un aggiornamento. Tuttavia, mantiene il software add-on sul cluster. Questa opzione rende il componente aggiuntivo un'installazione a gestione autonoma, piuttosto che un componente aggiuntivo Amazon EKS. Con questa opzione, il componente aggiuntivo non presenta tempi di inattività. Mantenere l' `--preserve` opzione nel comando per mantenere il componente aggiuntivo.
* *Rimozione del software aggiuntivo interamente dal cluster* – NetApp consiglia di rimuovere il componente aggiuntivo Amazon EKS dal cluster solo se non sono presenti risorse del cluster che dipendono da esso. Rimuovere l' `--preserve` opzione dal `delete` comando per rimuovere il componente aggiuntivo.



NOTE: Se al componente aggiuntivo è associato un account IAM, l'account IAM non viene rimosso.

[role="tabbed-block"]
====
.Console di gestione
--
. Aprire la console Amazon EKS all'indirizzo https://console.aws.amazon.com/eks/home#/clusters[].
. Nel riquadro di spostamento di sinistra, selezionare *cluster*.
. Selezionare il nome del cluster per il quale si desidera rimuovere il componente aggiuntivo NetApp Trident CSI.
. Selezionare la scheda *componenti aggiuntivi*, quindi selezionare *Trident by NetApp*.*
. Selezionare *Rimuovi*.
. Nella finestra di dialogo *Rimuovi conferma netapp_trident-operator*, esegui quanto segue:
+
.. Se si desidera che Amazon EKS smetta di gestire le impostazioni del componente aggiuntivo, selezionare *conserva su cluster*. Questa operazione consente di conservare il software aggiuntivo nel cluster in modo da poter gestire da soli tutte le impostazioni del componente aggiuntivo.
.. Immettere *netapp_trident-operator*.
.. Selezionare *Rimuovi*.




--
.CLI AWS
--
Sostituisci `my-cluster` con il nome del cluster ed esegui il seguente comando.

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksctl
--
Il seguente comando disinstalla il componente aggiuntivo Trident EKS:

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====