= 
:allow-uri-read: 


Trident Protect 24,10 e 24.10.1 e versioni successive garantiscono comportamenti diversi per la protezione delle applicazioni in esecuzione sulle macchine virtuali KubeVirt. Per entrambe le versioni, è possibile attivare o disattivare il blocco e lo sblocco del file system durante le operazioni di protezione dei dati.

[NOTE]
====
Per tutte le versioni di Trident Protect, per abilitare o disabilitare la funzionalità di blocco automatico negli ambienti OpenShift, potrebbe essere necessario concedere autorizzazioni privilegiate allo spazio dei nomi delle applicazioni. Ad esempio:

[source, console]
----
oc adm policy add-scc-to-user privileged -z default -n <application-namespace>
----
====
.Trident Protect 24,10
Trident Protect 24,10 non garantisce automaticamente uno stato coerente dei file system delle macchine virtuali KubeVirt durante le operazioni di protezione dei dati. Per proteggere i dati delle macchine virtuali KubeVirt utilizzando Trident Protect 24,10, è necessario abilitare manualmente la funzionalità di blocco/sblocco dei file system prima dell'operazione di protezione dei dati. Ciò garantisce che i filesystem siano in uno stato coerente.

È possibile configurare Trident Protect 24,10 per gestire il blocco e lo sblocco del file system della VM durante le operazioni di protezione dei dati link:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["configurazione della virtualizzazione"^]utilizzando il seguente comando:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
.Trident Protect 24.10.1 e versioni successive
A partire da Trident Protect 24.10.1, Trident Protect blocca e sblocca automaticamente i file system KubeVirt durante le operazioni di data Protection. Facoltativamente, è possibile disattivare questo comportamento automatico utilizzando il seguente comando:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----