---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: Prima di installare Trident, è necessario esaminare questi requisiti generali di sistema. I backend specifici potrebbero avere requisiti aggiuntivi. 
---
= Requisiti
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare Trident, è necessario esaminare questi requisiti generali di sistema. I backend specifici potrebbero avere requisiti aggiuntivi.



== Informazioni critiche su Trident

*È necessario leggere le seguenti informazioni critiche su Trident.*

.<strong> informazioni aggiornate su Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.35 è ora supportato in Trident. Aggiornare Trident prima di aggiornare Kubernetes.
* Trident impone rigorosamente l'uso della configurazione multipath negli ambienti SAN, con un valore consigliato di `find_multipaths: no` nel file multipath.conf.
+
Utilizzo di configurazioni o utilizzo non multipathing di `find_multipaths: yes` oppure `find_multipaths: smart` il valore nel file multipath.conf causerà errori di montaggio. Trident ha raccomandato l'uso di `find_multipaths: no` dalla release 21.07.



=====
====


== Frontend supportati (orchestratori)

Trident supporta molteplici motori e Orchestrator per container, tra cui:

* Anthos on-premise (VMware) e anthos su Bare Metal 1,16
* Kubernetes 1.27 - 1.35
* OpenShift 4.12, 4.14 - 4.20 (se si prevede di utilizzare la preparazione del nodo iSCSI con OpenShift 4.19, la versione minima supportata Trident è 25.06.1.)
+

NOTE: Trident continua a supportare le versioni precedenti di OpenShift in linea conlink:https://access.redhat.com/support/policy/updates/openshift["Ciclo di vita della versione Red Hat Extended Update Support (EUS)"] , anche se si basano su versioni di Kubernetes che non sono più ufficialmente supportate a monte.  In questi casi, durante l'installazione Trident , puoi tranquillamente ignorare eventuali messaggi di avviso relativi alla versione di Kubernetes.

* Rancher Kubernetes Engine 2 (RKE2) v1.28.x - 1.34.x
+

NOTE: _Sebbene Trident sia supportato su Rancher Kubernetes Engine 2 (RKE2) versioni 1.27.x - 1.34.x, Trident è attualmente qualificato solo su RKE2 v1.28.5+rke2r1._



Trident funziona anche con un host delle altre offerte Kubernetes completamente gestite e gestite in autonomia, tra cui Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Mirantis Kubernetes Engine (MKE) e il portfolio VMware Tanzu.

Trident e ONTAP possono essere utilizzati come provider di archiviazione per link:https://kubevirt.io/["KubeVirt"].


WARNING: Prima di aggiornare un cluster Kubernetes dalla versione 1,25 alla 1,26 o successiva in cui è installato Trident, fare riferimento alla link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation["Aggiornare un'installazione Helm"].



== Back-end supportati (storage)

Per utilizzare Trident, è necessario uno o più dei seguenti backend supportati:

* Amazon FSX per NetApp ONTAP
* Azure NetApp Files
* Cloud Volumes ONTAP
* Google Cloud NetApp Volumes
* Array All SAN (ASA) NetApp
* FAS, AFF o ASA r2 (iSCSI, NVMe/TCP e FC) in locale che eseguono versioni ONTAP con supporto NetApp completo o limitato. Vedere link:https://mysupport.netapp.com/site/info/version-support["Supporto della versione software"].
* Software NetApp HCI/Element 11 o superiore




== Supporto Trident per KubeVirt e OpenShift Virtualization

.Driver di archiviazione supportati:
Trident supporta i seguenti driver ONTAP per la virtualizzazione KubeVirt e OpenShift:

* ontap-nas
* economia di ONTAP-nas
* ONTAP-san (iSCSI, FCP, NVMe su TCP)
* ONTAP-san-Economy (solo iSCSI)


.Punti da considerare:
* Aggiornare la classe di archiviazione in modo che il `fsType` parametro (ad esempio: `fsType: "ext4"`) Nell'ambiente di virtualizzazione OpenShift. Se necessario, impostare la modalità volume in modo da bloccare esplicitamente utilizzando il `volumeMode=Block` parametro in `dataVolumeTemplates` per notificare a CDI la creazione di volumi di dati di blocco.
* _Modalità di accesso RWX per i driver di storage a blocchi_: I driver ONTAP-san (iSCSI, NVMe/TCP, FC) e ONTAP-san-Economy (iSCSI) sono supportati solo con "volumeMode: Block" (dispositivo raw). Per questi driver, il `fstype` parametro non può essere utilizzato perché i volumi sono forniti in modalità dispositivo raw.
* Per i flussi di lavoro di migrazione in tempo reale in cui è richiesta la modalità di accesso RWX, sono supportate le seguenti combinazioni:
+
** NFS + `volumeMode=Filesystem`
** ISCSI + `volumeMode=Block` (dispositivo raw)
** NVMe/TCP + `volumeMode=Block` (dispositivo raw)
** FC + `volumeMode=Block` (dispositivo raw)






== Requisiti delle funzionalità

La tabella seguente riassume le funzionalità disponibili con questa release di Trident e le versioni di Kubernetes che supporta.

[cols="3"]
|===
| Funzione | Versione di Kubernetes | Sono richiesti i gate delle funzionalità? 


| Trident  a| 
1.27 - 1.35
 a| 
No



| Snapshot dei volumi  a| 
1.27 - 1.35
 a| 
No



| PVC dalle istantanee dei volumi  a| 
1.27 - 1.35
 a| 
No



| Ridimensionamento di iSCSI PV  a| 
1.27 - 1.35
 a| 
No



| CHAP bidirezionale ONTAP  a| 
1.27 - 1.35
 a| 
No



| Policy di esportazione dinamiche  a| 
1.27 - 1.35
 a| 
No



| Operatore Trident  a| 
1.27 - 1.35
 a| 
No



| Topologia CSI  a| 
1.27 - 1.35
 a| 
No

|===


== Sistemi operativi host testati

Sebbene Trident non supporti ufficialmente sistemi operativi specifici, è noto che i seguenti sistemi funzionano:

* Versioni di Red Hat Enterprise Linux CoreOS (RHCOS) supportate da OpenShift Container Platform su AMD64 e ARM64
* Red Hat Enterprise Linux (RHEL) 8 o versione successiva su AMD64 e ARM64
+

NOTE: NVMe/TCP richiede RHEL 9 o versione successiva.

* Ubuntu 22.04 LTS o successivo su AMD64 e ARM64
* Windows Server 2022
* SUSE Linux Enterprise Server (SLES) 15 o versione successiva


Per impostazione predefinita, Trident viene eseguito in un container e quindi viene eseguito su qualsiasi lavoratore Linux. Tuttavia, tali dipendenti devono essere in grado di montare i volumi forniti da Trident utilizzando il client NFS standard o l'iniziatore iSCSI, a seconda dei backend in uso.

Il `tridentctl` Utility può essere eseguita anche su una qualsiasi di queste distribuzioni di Linux.



== Configurazione dell'host

Tutti i nodi di lavoro nel cluster Kubernetes devono essere in grado di montare i volumi forniti per i pod. Per preparare i nodi di lavoro, devi installare i tool NFS, iSCSI o NVMe in base alla tua selezione di driver.

link:../trident-use/worker-node-prep.html["Preparare il nodo di lavoro"]



== Configurazione del sistema storage

Trident potrebbe richiedere modifiche a un sistema di storage prima che possa essere utilizzato da una configurazione backend.

link:../trident-use/backends.html["Configurare i backend"]



== Porte Trident

Trident richiede l'accesso a porte specifiche per la comunicazione.

link:../trident-reference/ports.html["Porte Trident"]



== Immagini container e corrispondenti versioni di Kubernetes

Per le installazioni con montaggio ad aria, l'elenco seguente è un riferimento alle immagini contenitore necessarie per installare Trident. Utilizzare il `tridentctl images` comando per verificare l'elenco delle immagini contenitore necessarie.



=== Immagini container necessarie per Trident 26.02

[cols="2"]
|===
| Versioni di Kubernetes | Immagine container 


| v1.27.0, v1.28.0, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.34.0, v1.35.0  a| 
* docker.io/netapp/trident:26.02.0
* docker.io/netapp/trident-autosupport:25.10
* registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
* registry.k8s.io/sig-storage/csi-attacher:v4.10.0
* registry.k8s.io/sig-storage/csi-resizer:v1.14.0
* registry.k8s.io/sig-storage/csi-snapshotter:v8.3.0
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0
* docker.io/netapp/trident-operator:25.10.0 (facoltativo)


|===