---
sidebar: sidebar 
permalink: trident-concepts/snapshots.html 
keywords: provisioning, Trident 
summary: Scopri di più su come Trident gestisce la creazione di snapshot di volume per i driver. 
---
= Snapshot dei volumi
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri di più su come Trident gestisce la creazione di snapshot di volume per i driver.



== Scopri di più sulla creazione di snapshot di volumi

* Per il `ontap-nas` , `ontap-san` , E `azure-netapp-files` driver, ogni Persistent Volume (PV) viene mappato su un FlexVol volume. Di conseguenza, gli snapshot del volume vengono creati come snapshot NetApp . La tecnologia snapshot NetApp offre maggiore stabilità, scalabilità, recuperabilità e prestazioni rispetto alle tecnologie snapshot della concorrenza. Queste copie snapshot sono estremamente efficienti sia in termini di tempo necessario per crearle sia di spazio di archiviazione.
* Per `ontap-nas-flexgroup` Driver, ogni volume persistente (PV) viene mappato su un FlexGroup. Di conseguenza, le snapshot dei volumi vengono create come snapshot NetApp FlexGroup. La tecnologia NetApp Snapshot offre più stabilità, scalabilità, ripristinabilità e performance rispetto alle tecnologie Snapshot concorrenti. Queste copie Snapshot sono estremamente efficienti sia nel tempo necessario per crearle che nello spazio di storage.
* Per il `ontap-san-economy` driver, i PV vengono mappati alle LUN create su volumi FlexVol condivisi VolumeSnapshot di PVS vengono ottenuti eseguendo FlexClone della LUN associata. La tecnologia ONTAP FlexClone consente di creare copie anche dei set di dati più estesi in maniera quasi istantanea. Le copie condividono i blocchi di dati con i genitori, senza consumare storage ad eccezione di quanto richiesto per i metadati.
* Per `solidfire-san` Driver, ogni PV viene mappato su un LUN creato nel software NetApp Element/cluster NetApp HCI. Le istantanee Volumesono rappresentate da snapshot degli elementi del LUN sottostante. Queste snapshot sono copie point-in-time e occupano solo una piccola quantità di risorse e spazio di sistema.
* Quando si lavora con `ontap-nas` i driver e `ontap-san`, le snapshot ONTAP sono copie point-in-time della FlexVol e consumano spazio sulla FlexVol stessa. Ciò può comportare una riduzione dello spazio scrivibile nel volume durante la creazione/pianificazione delle istantanee. Un modo semplice per risolvere questo problema consiste nell'aumentare il volume ridimensionandolo tramite Kubernetes. Un'altra opzione consiste nell'eliminare gli snapshot non più necessari. Quando un VolumeSnapshot creato tramite Kubernetes viene eliminato, Trident eliminerà lo snapshot ONTAP associato. È possibile eliminare anche gli snapshot ONTAP non creati tramite Kubernetes.


Con Trident, puoi usare VolumeSnapshots per creare nuovi PV da essi. La creazione di PV da questi snapshot viene eseguita utilizzando la tecnologia FlexClone per i backend ONTAP supportati. Quando si crea un PV da uno snapshot, il volume di supporto è un FlexClone del volume padre dello snapshot. IL `solidfire-san` il driver utilizza cloni di volume del software Element per creare PV da snapshot. Qui viene creato un clone dallo snapshot dell'Elemento.
