---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: 'Inizia subito con la verifica della prontezza del tuo ambiente operativo, dei cluster di applicazioni, delle applicazioni e delle licenze. Assicurati che il tuo ambiente soddisfi questi requisiti per l"implementazione e l"utilizzo di Trident Protect.' 
---
= Requisiti di Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Inizia subito con la verifica della prontezza del tuo ambiente operativo, dei cluster di applicazioni, delle applicazioni e delle licenze. Assicurati che il tuo ambiente soddisfi questi requisiti per l'implementazione e l'utilizzo di Trident Protect.



== Trident protegge la compatibilità del cluster Kubernetes

Trident Protect è compatibile con un'ampia gamma di offerte Kubernetes completamente gestite e autogestite, tra cui:

* Amazon Elastic Kubernetes Service (EKS)
* Google Kubernetes Engine (GKE)
* Servizio Kubernetes di Microsoft Azure (AKS)
* Red Hat OpenShift
* SUSE Rancher
* Portfolio VMware Tanzu
* Kubernetes upstream



NOTE: Assicurarsi che il cluster su cui si installa Trident Protect sia configurato con un controller snapshot in esecuzione e i CRD correlati. Per installare un'unità di controllo istantanee, fare riferimento alla https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["queste istruzioni"].



== Trident protegge la compatibilità del backend di storage

Trident Protect supporta i seguenti backend di storage:

* Amazon FSX per NetApp ONTAP
* Cloud Volumes ONTAP
* Array storage ONTAP
* Google Cloud NetApp Volumes
* Azure NetApp Files


Verificare che lo storage backend soddisfi i seguenti requisiti:

* Assicurati che lo storage NetApp connesso al cluster stia utilizzando Astra Trident 24,02 o versione successiva (si consiglia Trident 24,10).
+
** Se Astra Trident è precedente alla versione 24.06.1 e intendi utilizzare la funzionalità di disaster recovery di NetApp SnapMirror, devi attivare manualmente Astra Control Provisioner.


* Assicurati di avere l'ultima versione di Astra Control Provisioner (installata e abilitata per impostazione predefinita a partire da Astra Trident 24.06.1).
* Verificare di disporre di un back-end dello storage NetApp ONTAP.
* Verificare di aver configurato un bucket dello storage a oggetti per la memorizzazione dei backup.
* Creare spazi dei nomi delle applicazioni che si intende utilizzare per applicazioni o operazioni di gestione dei dati delle applicazioni. Trident Protect non crea questi spazi dei nomi per l'utente; se si specifica uno spazio dei nomi inesistente in una risorsa personalizzata, l'operazione non verrà eseguita correttamente.




== Per i volumi nas-Economy

Trident Protect supporta le operazioni di backup e ripristino su volumi nas-Economy. Al momento snapshot, cloni e replica SnapMirror sui volumi nas-Economy non sono supportati. È necessario abilitare una directory di snapshot per ogni volume economico nas che si intende utilizzare con Trident Protect.

[NOTE]
====
Alcune applicazioni non sono compatibili con volumi che utilizzano una directory snapshot. Per queste applicazioni, è necessario nascondere la directory dello snapshot eseguendo il seguente comando nel sistema di archiviazione ONTAP:

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
Puoi abilitare la directory dello snapshot eseguendo il seguente comando per ogni volume di economia nas, sostituendo `<volume-UUID>` con l'UUID del volume che desideri modificare:

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: Per impostazione predefinita, è possibile abilitare le directory snapshot per i nuovi volumi impostando l'opzione di configurazione back-end Trident `snapshotDir` su `true`. I volumi esistenti non vengono influenzati.



== Protezione dei dati con le macchine virtuali KubeVirt

Trident Protect 24,10 e 24.10.1 e versioni successive garantiscono comportamenti diversi per la protezione delle applicazioni in esecuzione sulle macchine virtuali KubeVirt. Per entrambe le versioni, è possibile attivare o disattivare il blocco e lo sblocco del file system durante le operazioni di protezione dei dati.

[NOTE]
====
Per tutte le versioni di Trident Protect, per abilitare o disabilitare la funzionalità di blocco automatico negli ambienti OpenShift, potrebbe essere necessario concedere autorizzazioni privilegiate allo spazio dei nomi delle applicazioni. Ad esempio:

[source, console]
----
oc adm policy add-scc-to-user privileged -z default -n <application-namespace>
----
====
.Trident Protect 24,10
Trident Protect 24,10 non garantisce automaticamente uno stato coerente dei file system delle macchine virtuali KubeVirt durante le operazioni di protezione dei dati. Per proteggere i dati delle macchine virtuali KubeVirt utilizzando Trident Protect 24,10, è necessario abilitare manualmente la funzionalità di blocco/sblocco dei file system prima dell'operazione di protezione dei dati. Ciò garantisce che i filesystem siano in uno stato coerente.

È possibile configurare Trident Protect 24,10 per gestire il blocco e lo sblocco del file system della VM durante le operazioni di protezione dei dati link:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["configurazione della virtualizzazione"^]utilizzando il seguente comando:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
.Trident Protect 24.10.1 e versioni successive
A partire da Trident Protect 24.10.1, Trident Protect blocca e sblocca automaticamente i file system KubeVirt durante le operazioni di data Protection. Facoltativamente, è possibile disattivare questo comportamento automatico utilizzando il seguente comando:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----


== Requisiti per la replica SnapMirror

NetApp SnapMirror è disponibile per l'uso con Trident Protect per le seguenti soluzioni ONTAP:

* NetApp ASA
* NetApp AFF
* NetApp FAS
* NetApp ONTAP Select
* NetApp Cloud Volumes ONTAP
* Amazon FSX per NetApp ONTAP




=== Requisiti del cluster di ONTAP per la replica SnapMirror

Assicurati che il tuo cluster ONTAP soddisfi i seguenti requisiti se intendi utilizzare la replica SnapMirror:

* *Astra Control Provisioner o Trident*: Astra Control Provisioner o Trident deve esistere sia sui cluster Kubernetes di origine che di destinazione che utilizzano ONTAP come backend. Trident Protect supporta la replica con la tecnologia NetApp SnapMirror utilizzando classi di storage supportate dai seguenti driver:
+
** `ontap-nas`
** `ontap-san`


* *Licenze*: Le licenze asincrone di ONTAP SnapMirror che utilizzano il bundle di protezione dati devono essere attivate sia sul cluster ONTAP di origine che su quello di destinazione. Per ulteriori informazioni, fare riferimento https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["Panoramica sulle licenze SnapMirror in ONTAP"^] a.




=== Considerazioni sul peering per la replica SnapMirror

Assicurati che il tuo ambiente soddisfi i seguenti requisiti se intendi utilizzare il peering di back-end dello storage:

* *Cluster e SVM*: I backend dello storage ONTAP devono essere peering. Per ulteriori informazioni, fare riferimento https://docs.netapp.com/us-en/ontap/peering/index.html["Panoramica del peering di cluster e SVM"^] a.
+

NOTE: Assicurati che i nomi delle SVM utilizzati nella relazione di replica tra due cluster ONTAP siano univoci.

* *Astra Control Provisioner o Trident e SVM*: Le SVM remote in fase di migrazione devono essere disponibili per Astra Control Provisioner o Trident nel cluster di destinazione.
* *Backend gestiti*: È necessario aggiungere e gestire i backend di storage ONTAP in Trident Protect per creare una relazione di replica.
* *NVMe over TCP*: Trident Protect non supporta la replica NetApp SnapMirror per backend di storage che utilizzano il protocollo NVMe over TCP.




=== Configurazione Trident / ONTAP per la replica SnapMirror

Trident Protect richiede la configurazione di almeno un backend di storage che supporti la replica per i cluster di origine e di destinazione. Se i cluster di origine e di destinazione sono gli stessi, l'applicazione di destinazione deve utilizzare un backend di storage diverso da quello dell'applicazione di origine per ottenere la migliore resilienza.
