---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: 'Puoi aggiornare Trident Protect all"ultima versione per sfruttare le nuove funzionalità o le correzioni di bug.' 
---
= Aggiorna Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puoi aggiornare Trident Protect all'ultima versione per sfruttare le nuove funzionalità o le correzioni di bug.

[NOTE]
====
* Quando si esegue l'aggiornamento dalla versione 24.10, gli snapshot in esecuzione durante l'aggiornamento potrebbero non funzionare. Questo problema non impedisce la creazione di snapshot futuri, manuali o pianificati. Se uno snapshot non funziona durante l'aggiornamento, è possibile crearne manualmente uno nuovo per garantire la protezione dell'applicazione.
+
Per evitare potenziali errori, è possibile disabilitare tutte le pianificazioni degli snapshot prima dell'aggiornamento e riabilitarle in seguito. Tuttavia, ciò comporterà la perdita di tutti gli snapshot pianificati durante il periodo di aggiornamento.

* Per le installazioni di registri privati, assicurati che il grafico Helm e le immagini richiesti per la versione di destinazione siano disponibili nel tuo registro privato e verifica che i tuoi valori Helm personalizzati siano compatibili con la nuova versione del grafico. Per maggiori informazioni, fare riferimento alink:trident-protect-installation.html["Installa Trident Protect da un registro privato"] .


====


== Fase 1: Selezionare una versione

Le versioni di Trident Protect seguono una convenzione di naming basata sulla data  `YY.MM`, dove "YY" sono le ultime due cifre dell'anno e "MM" è il mese. Le versioni Dot seguono una convenzione  `YY.MM.X`, dove "X" è il livello di patch. Selezionerai la versione a cui eseguire l'aggiornamento in base alla versione da cui stai aggiornando.

* È possibile eseguire un aggiornamento diretto a qualsiasi release di destinazione che rientri in una finestra di quattro release della versione installata. Ad esempio, è possibile eseguire un aggiornamento diretto dalla 24.10 (o da qualsiasi 24.10 dot release) alla 25.10.
* Se si esegue l'aggiornamento da una release al di fuori della finestra di quattro release, eseguire un aggiornamento in più fasi. Usare le istruzioni di aggiornamento per la link:../earlier-versions.html["versione precedente"] da cui si esegue l'aggiornamento per passare alla release più recente che rientra nella finestra di quattro release. Ad esempio, se si sta eseguendo la 24.10 e si desidera eseguire l'aggiornamento alla 26.02:
+
.. Primo upgrade dal 24.10 al 25.02.
.. Quindi esegui l'aggiornamento da 25.02 a 26.02.






== Passaggio 2: Aggiornare Trident Protect

Per aggiornare Trident Protect, procedere come segue.

.Fasi
. Aggiornare il repository di Trident Helm:
+
[source, console]
----
helm repo update
----
. Aggiorna i CRD Trident Protect:
+

NOTE: Questo passaggio è necessario se si esegue l'aggiornamento da una versione precedente alla 25.06, poiché i CRD sono ora inclusi nella tabella Trident Protect Helm.

+
.. Eseguire questo comando per spostare la gestione dei CRD da  `trident-protect-crds` A  `trident-protect` :
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
.. Esegui questo comando per eliminare il segreto Helm per  `trident-protect-crds` grafico:
+

NOTE: Non disinstallare il  `trident-protect-crds` grafico utilizzando Helm, poiché ciò potrebbe rimuovere i CRD e tutti i dati correlati.

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Aggiorna Trident Protect:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2510.0 --namespace trident-protect
----
+

NOTE: È possibile configurare il livello di registrazione durante l'aggiornamento aggiungendo `--set logLevel=debug` al comando di aggiornamento. Il livello di registrazione predefinito è `warn` . La registrazione del debug è consigliata per la risoluzione dei problemi, poiché aiuta il supporto NetApp a diagnosticare i problemi senza richiedere modifiche al livello di registro o la riproduzione del problema.


