---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: 'Se l"ambiente in uso soddisfa i requisiti, è possibile seguire questi passaggi per installare Trident Protect.' 
---
= Installare e configurare Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se l'ambiente in uso soddisfa i requisiti di Trident Protect, è possibile seguire questa procedura per installare Trident Protect sul cluster. È possibile ottenere Trident Protect da NetApp o installarlo dal proprio registro privato. L'installazione da un registro privato è utile se il cluster non riesce ad accedere a Internet.



== Installare Trident Protect

[role="tabbed-block"]
====
.Installare Trident Protect di NetApp
--
.Fasi
. Aggiungere il repository Trident Helm:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Utilizzare Helm per installare Trident Protect. Sostituire `<name-of-cluster>` con un nome cluster, che verrà assegnato al cluster e utilizzato per identificare i backup e gli snapshot del cluster:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --version 100.2506.0 --create-namespace --namespace trident-protect
----


--
.Installare Trident Protect da un registro privato
--
È possibile installare Trident Protect da un registro di immagine privata se il cluster Kubernetes non è in grado di accedere a Internet. In questi esempi, sostituire i valori tra parentesi con le informazioni dell'ambiente:

.Fasi
. Estrarre le seguenti immagini sul computer locale, aggiornare i tag e quindi inviarle al registro privato:
+
[source, console]
----
docker.io/netapp/controller:25.06.0
docker.io/netapp/restic:25.06.0
docker.io/netapp/kopia:25.06.0
docker.io/netapp/kopiablockrestore:25.06.0
docker.io/netapp/trident-autosupport:25.06.0
docker.io/netapp/exechook:25.06.0
docker.io/netapp/resourcebackup:25.06.0
docker.io/netapp/resourcerestore:25.06.0
docker.io/netapp/resourcedelete:25.06.0
docker.io/bitnami/kubectl:1.30.2
gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0
----
+
Ad esempio:

+
[source, console]
----
docker pull docker.io/netapp/controller:25.06.0
----
+
[source, console]
----
docker tag docker.io/netapp/controller:25.06.0 <private-registry-url>/controller:25.06.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:25.06.0
----
+

NOTE: Per ottenere la tabella Helm, scaricare prima la tabella Helm su un computer con accesso a Internet utilizzando `helm pull trident-protect --version 100.2506.0 --repo https://netapp.github.io/trident-protect-helm-chart`, quindi copia il risultato `trident-protect-100.2506.0.tgz` file nel tuo ambiente offline e installalo utilizzando `helm install trident-protect ./trident-protect-100.2506.0.tgz` invece del riferimento al repository nel passaggio finale.

. Creare lo spazio dei nomi del sistema Trident Protect:
+
[source, console]
----
kubectl create ns trident-protect
----
. Accedere al Registro di sistema:
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. Creare un segreto pull da utilizzare per l'autenticazione privata del Registro di sistema:
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. Aggiungere il repository Trident Helm:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Creare un file denominato `protectValues.yaml`. Verificare che contenga le seguenti impostazioni di protezione Trident:
+
[source, yaml]
----
---
controller:
  image:
    registry: <private-registry-url>
rbacProxy:
  image:
    registry: <private-registry-url>
crCleanup:
  imagePullSecrets:
    - name: regcred
webhooksCleanup:
  imagePullSecrets:
    - name: regcred
----
+

NOTE: IL `controller.image.registry` l'impostazione si applica a tutte le immagini dei componenti, comprese `resourcebackup` E `resourcerestore`. Se si inseriscono immagini in un percorso di repository specifico all'interno del registro (ad esempio, `example.com:443/my-repo`), includere il percorso completo nel campo del registro. Ciò garantirà che tutte le immagini vengano estratte da `<private-registry-url>/<image-name>:<tag>`.

. Utilizzare Helm per installare Trident Protect. Sostituire `<name_of_cluster>` con un nome cluster, che verrà assegnato al cluster e utilizzato per identificare i backup e gli snapshot del cluster:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2506.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----


--
====

NOTE: Per ulteriori opzioni di configurazione del grafico Helm, incluse le impostazioni AutoSupport e il filtraggio dello spazio dei nomi, fare riferimento a link:trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Personalizzare l'installazione di Trident Protect"].
