---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: 'Inizia subito con la verifica della prontezza del tuo ambiente operativo, dei cluster di applicazioni, delle applicazioni e delle licenze. Assicurati che il tuo ambiente soddisfi questi requisiti per l"implementazione e l"utilizzo di Trident Protect.' 
---
= Requisiti di Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Inizia subito con la verifica della prontezza del tuo ambiente operativo, dei cluster di applicazioni, delle applicazioni e delle licenze. Assicurati che il tuo ambiente soddisfi questi requisiti per l'implementazione e l'utilizzo di Trident Protect.



== Trident protegge la compatibilità del cluster Kubernetes

Trident Protect è compatibile con un'ampia gamma di offerte Kubernetes completamente gestite e autogestite, tra cui:

* Amazon Elastic Kubernetes Service (EKS)
* Google Kubernetes Engine (GKE)
* Servizio Kubernetes di Microsoft Azure (AKS)
* Red Hat OpenShift
* SUSE Rancher
* Portfolio VMware Tanzu
* Kubernetes upstream


[NOTE]
====
* I backup Trident Protect sono supportati solo sui nodi di elaborazione Linux.  I nodi di elaborazione Windows non sono supportati per le operazioni di backup.
* Assicurarsi che il cluster su cui si installa Trident Protect sia configurato con un controller snapshot in esecuzione e i CRD correlati. Per installare un'unità di controllo istantanee, fare riferimento alla https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["queste istruzioni"].


====


== Trident protegge la compatibilità del backend di storage

Trident Protect supporta i seguenti backend di storage:

* Amazon FSX per NetApp ONTAP
* Cloud Volumes ONTAP
* Array storage ONTAP
* Google Cloud NetApp Volumes
* Azure NetApp Files


Verificare che lo storage backend soddisfi i seguenti requisiti:

* Assicurarsi che lo storage NetApp connesso al cluster utilizzi Trident 24.02 o una versione successiva (si consiglia Trident 24.10).


* Verificare di disporre di un back-end dello storage NetApp ONTAP.
* Verificare di aver configurato un bucket dello storage a oggetti per la memorizzazione dei backup.
* Creare spazi dei nomi delle applicazioni che si intende utilizzare per applicazioni o operazioni di gestione dei dati delle applicazioni. Trident Protect non crea questi spazi dei nomi per l'utente; se si specifica uno spazio dei nomi inesistente in una risorsa personalizzata, l'operazione non verrà eseguita correttamente.




== Per i volumi nas-Economy

Trident Protect supporta le operazioni di backup e ripristino su volumi nas-Economy. Al momento snapshot, cloni e replica SnapMirror sui volumi nas-Economy non sono supportati. È necessario abilitare una directory di snapshot per ogni volume economico nas che si intende utilizzare con Trident Protect.

[NOTE]
====
Alcune applicazioni non sono compatibili con volumi che utilizzano una directory snapshot. Per queste applicazioni, è necessario nascondere la directory dello snapshot eseguendo il seguente comando nel sistema di archiviazione ONTAP:

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
Puoi abilitare la directory dello snapshot eseguendo il seguente comando per ogni volume di economia nas, sostituendo `<volume-UUID>` con l'UUID del volume che desideri modificare:

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: Per impostazione predefinita, è possibile abilitare le directory snapshot per i nuovi volumi impostando l'opzione di configurazione back-end Trident `snapshotDir` su `true`. I volumi esistenti non vengono influenzati.



== Protezione dei dati con le macchine virtuali KubeVirt

Trident Protect fornisce funzionalità di blocco e sblocco del file system per le macchine virtuali KubeVirt durante le operazioni di protezione dei dati per garantire la coerenza dei dati. Il metodo di configurazione e il comportamento predefinito per le operazioni di congelamento delle VM variano a seconda delle versioni Trident Protect, con le versioni più recenti che offrono una configurazione semplificata tramite i parametri del grafico Helm.


NOTE: Durante le operazioni di ripristino, qualsiasi  `VirtualMachineSnapshots` creati per una macchina virtuale (VM) non vengono ripristinati.

.Trident Protect 25.10 e versioni successive
[%collapsible%open]
====
Trident Protect blocca e sblocca automaticamente i file system KubeVirt durante le operazioni di protezione dei dati per garantire la coerenza. A partire da Trident Protect 25.10, è possibile disattivare questo comportamento utilizzando `vm.freeze` parametro durante l'installazione della carta Helm. Il parametro è abilitato per impostazione predefinita.

[source, console]
----
helm install ... --set vm.freeze=false ...
----
====
.Trident Protect dal 24.10.1 al 25.06
[%collapsible]
====
A partire da Trident Protect 24.10.1, Trident Protect blocca e sblocca automaticamente i file system KubeVirt durante le operazioni di data Protection. Facoltativamente, è possibile disattivare questo comportamento automatico utilizzando il seguente comando:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----
====
.Trident Protect 24,10
[%collapsible]
====
Trident Protect 24,10 non garantisce automaticamente uno stato coerente dei file system delle macchine virtuali KubeVirt durante le operazioni di protezione dei dati. Per proteggere i dati delle macchine virtuali KubeVirt utilizzando Trident Protect 24,10, è necessario abilitare manualmente la funzionalità di blocco/sblocco dei file system prima dell'operazione di protezione dei dati. Ciò garantisce che i filesystem siano in uno stato coerente.

È possibile configurare Trident Protect 24,10 per gestire il blocco e lo sblocco del file system della VM durante le operazioni di protezione dei dati link:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["configurazione della virtualizzazione"^]utilizzando il seguente comando:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
====


== Requisiti per la replica SnapMirror

La replica di NetApp SnapMirror è disponibile per l'utilizzo con Trident Protect per le seguenti soluzioni ONTAP:

* Cluster NetApp FAS, AFF e ASA on-premise
* NetApp ONTAP Select
* NetApp Cloud Volumes ONTAP
* Amazon FSX per NetApp ONTAP




=== Requisiti del cluster di ONTAP per la replica SnapMirror

Assicurati che il tuo cluster ONTAP soddisfi i seguenti requisiti se intendi utilizzare la replica SnapMirror:

* *NetApp Trident*: NetApp Trident deve essere presente sia sul cluster Kubernetes di origine che su quello di destinazione che utilizzano ONTAP come backend. Trident Protect supporta la replica con la tecnologia NetApp SnapMirror utilizzando classi di storage supportate dai seguenti driver:
+
** `ontap-nas` : NFS
** `ontap-san` : iSCSI
** `ontap-san` : FC
** `ontap-san` : NVMe/TCP (richiede almeno la versione ONTAP 9.15.1)


* *Licenze*: Le licenze asincrone di ONTAP SnapMirror che utilizzano il bundle di protezione dati devono essere attivate sia sul cluster ONTAP di origine che su quello di destinazione. Per ulteriori informazioni, fare riferimento https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["Panoramica sulle licenze SnapMirror in ONTAP"^] a.
+
A partire da ONTAP 9.10.1, tutte le licenze vengono fornite come file di licenza NetApp (NLF), che è un singolo file che abilita più funzioni. Per ulteriori informazioni, fare riferimento link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licenze incluse con ONTAP ONE"^] a.

+

NOTE: È supportata solo la protezione asincrona SnapMirror.





=== Considerazioni sul peering per la replica SnapMirror

Assicurati che il tuo ambiente soddisfi i seguenti requisiti se intendi utilizzare il peering di back-end dello storage:

* *Cluster e SVM*: I backend dello storage ONTAP devono essere peering. Per ulteriori informazioni, fare riferimento https://docs.netapp.com/us-en/ontap/peering/index.html["Panoramica del peering di cluster e SVM"^] a.
+

NOTE: Assicurati che i nomi delle SVM utilizzati nella relazione di replica tra due cluster ONTAP siano univoci.

* *NetApp Trident e SVM*: le SVM remote peered devono essere disponibili per NetApp Trident sul cluster di destinazione.
* *Backend gestiti*: È necessario aggiungere e gestire i backend di storage ONTAP in Trident Protect per creare una relazione di replica.




=== Configurazione Trident / ONTAP per la replica SnapMirror

Trident Protect richiede la configurazione di almeno un backend di storage che supporti la replica per i cluster di origine e di destinazione. Se i cluster di origine e di destinazione sono gli stessi, l'applicazione di destinazione deve utilizzare un backend di storage diverso da quello dell'applicazione di origine per ottenere la migliore resilienza.



=== Requisiti del cluster Kubernetes per la replica SnapMirror

Assicurati che i tuoi cluster Kubernetes soddisfino i seguenti requisiti:

* *Accessibilità ad AppVault*: sia i cluster di origine che quelli di destinazione devono avere accesso alla rete per leggere e scrivere su AppVault per la replica degli oggetti applicativi.
* *Connettività di rete*: configura le regole del firewall, le autorizzazioni dei bucket e le liste consentite di IP per abilitare la comunicazione tra entrambi i cluster e AppVault attraverso le WAN.



NOTE: Molti ambienti aziendali implementano rigide policy firewall sulle connessioni WAN.  Verificare questi requisiti di rete con il team dell'infrastruttura prima di configurare la replica.
