---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: 'Inizia subito con la verifica della prontezza del tuo ambiente operativo, dei cluster di applicazioni, delle applicazioni e delle licenze. Assicurati che il tuo ambiente soddisfi questi requisiti per l"implementazione e l"utilizzo di Trident Protect.' 
---
= Requisiti di Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Inizia subito con la verifica della prontezza del tuo ambiente operativo, dei cluster di applicazioni, delle applicazioni e delle licenze. Assicurati che il tuo ambiente soddisfi questi requisiti per l'implementazione e l'utilizzo di Trident Protect.



== Trident protegge la compatibilità di Kubernetes

Trident Protect è compatibile con un'ampia gamma di offerte Kubernetes completamente gestite e autogestite, tra cui:

* Amazon Elastic Kubernetes Service (EKS)
* Google Kubernetes Engine (GKE)
* Servizio Kubernetes di Microsoft Azure (AKS)
* Red Hat OpenShift
* SUSE Rancher
* Portfolio VMware Tanzu
* Kubernetes upstream




== Trident protegge la compatibilità del backend di storage

Trident Protect supporta i seguenti backend di storage:

* Amazon FSX per NetApp ONTAP
* Cloud Volumes ONTAP
* Array storage ONTAP
* Google Cloud NetApp Volumes
* Azure NetApp Files


Verificare che lo storage backend soddisfi i seguenti requisiti:

* Assicurati che lo storage NetApp connesso al cluster stia utilizzando Astra Trident 24,02 o versione successiva (si consiglia Trident 24,10).
+
** Se Astra Trident è precedente alla versione 24.06.1 e intendi utilizzare la funzionalità di disaster recovery di NetApp SnapMirror, devi attivare manualmente Astra Control Provisioner.


* Assicurati di avere l'ultima versione di Astra Control Provisioner (installata e abilitata per impostazione predefinita a partire da Astra Trident 24.06.1).
* Verificare di disporre di un back-end dello storage NetApp ONTAP.
* Verificare di aver configurato un bucket dello storage a oggetti per la memorizzazione dei backup.
* Creare spazi dei nomi delle applicazioni che si intende utilizzare per applicazioni o operazioni di gestione dei dati delle applicazioni. Trident Protect non crea questi spazi dei nomi per l'utente; se si specifica uno spazio dei nomi inesistente in una risorsa personalizzata, l'operazione non verrà eseguita correttamente.




== Per i volumi nas-Economy

Trident Protect supporta le operazioni di backup e ripristino su volumi nas-Economy. Al momento snapshot, cloni e replica SnapMirror sui volumi nas-Economy non sono supportati. È necessario abilitare una directory di snapshot per ogni volume economico nas che si intende utilizzare con Trident Protect.

[NOTE]
====
Alcune applicazioni non sono compatibili con volumi che utilizzano una directory snapshot. Per queste applicazioni, è necessario nascondere la directory dello snapshot eseguendo il seguente comando nel sistema di archiviazione ONTAP:

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
Puoi abilitare la directory dello snapshot eseguendo il seguente comando per ogni volume di economia nas, sostituendo `<volume-UUID>` con l'UUID del volume che desideri modificare:

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: Per impostazione predefinita, è possibile abilitare le directory snapshot per i nuovi volumi impostando l'opzione di configurazione back-end Trident `snapshotDir` su `true`. I volumi esistenti non vengono influenzati.



== Requisiti per la replica SnapMirror

NetApp SnapMirror è disponibile per l'uso con Trident Protect per le seguenti soluzioni ONTAP:

* NetApp ASA
* NetApp AFF
* NetApp FAS
* NetApp ONTAP Select
* NetApp Cloud Volumes ONTAP
* Amazon FSX per NetApp ONTAP




=== Requisiti del cluster di ONTAP per la replica SnapMirror

Assicurati che il tuo cluster ONTAP soddisfi i seguenti requisiti se intendi utilizzare la replica SnapMirror:

* *Astra Control Provisioner o Trident*: Astra Control Provisioner o Trident deve esistere sia sui cluster Kubernetes di origine che di destinazione che utilizzano ONTAP come backend. Trident Protect supporta la replica con la tecnologia NetApp SnapMirror utilizzando classi di storage supportate dai seguenti driver:
+
** `ontap-nas`
** `ontap-san`


* *Licenze*: Le licenze asincrone di ONTAP SnapMirror che utilizzano il bundle di protezione dati devono essere attivate sia sul cluster ONTAP di origine che su quello di destinazione. Per ulteriori informazioni, fare riferimento https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["Panoramica sulle licenze SnapMirror in ONTAP"^] a.




=== Considerazioni sul peering per la replica SnapMirror

Assicurati che il tuo ambiente soddisfi i seguenti requisiti se intendi utilizzare il peering di back-end dello storage:

* *Cluster e SVM*: I backend dello storage ONTAP devono essere peering. Per ulteriori informazioni, fare riferimento https://docs.netapp.com/us-en/ontap/peering/index.html["Panoramica del peering di cluster e SVM"^] a.
+

NOTE: Assicurati che i nomi delle SVM utilizzati nella relazione di replica tra due cluster ONTAP siano univoci.

* *Astra Control Provisioner o Trident e SVM*: Le SVM remote in fase di migrazione devono essere disponibili per Astra Control Provisioner o Trident nel cluster di destinazione.
* *Backend gestiti*: È necessario aggiungere e gestire i backend di storage ONTAP in Trident Protect per creare una relazione di replica.
* *NVMe over TCP*: Trident Protect non supporta la replica NetApp SnapMirror per backend di storage che utilizzano il protocollo NVMe over TCP.




=== Configurazione Trident / ONTAP per la replica SnapMirror

Trident Protect richiede la configurazione di almeno un backend di storage che supporti la replica per i cluster di origine e di destinazione. Se i cluster di origine e di destinazione sono gli stessi, l'applicazione di destinazione deve utilizzare un backend di storage diverso da quello dell'applicazione di origine per ottenere la migliore resilienza.



=== Considerazioni sull'utilizzo di KubeVirt

Se si intende utilizzare https://kubevirt.io/["KubeVirt"^] macchine virtuali con replica SnapMirror, è necessario configurare una virtualizzazione in modo da poter bloccare e sbloccare le SVM. Dopo aver configurato la virtualizzazione, le SVM implementate includeranno i tool necessari per il congelamento e lo sblocco. Per ulteriori informazioni sull'impostazione della virtualizzazione, fare riferimento a https://docs.openshift.com/container-platform/4.17/virt/install/installing-virt.html["Installazione di OpenShift Virtualization"^].
